# from https://github.com/japaric/rust-everywhere and https://github.com/yupferris/rustendo64/blob/master/appveyor.yml

os: Visual Studio 2015

environment:
  global:
    # This will be used as part of the zipfile name
    PROJECT_NAME: rusoto
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
cache:
  - 'C:\Users\appveyor\.cargo'
# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;c:\cygwin\bin
  - rustc -Vv
  - cargo -V

build: false
test_script:
  - cd rusoto && cargo test --all --lib

branches:
  only:
    - master
